import React from 'react';

function About() {
    return (
        <>
        <h1>About</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus unde, harum facere, suscipit obcaecati itaque necessitatibus repudiandae voluptatum fuga ullam atque laboriosam recusandae porro quidem dolorum, maiores tenetur ratione aliquid ipsa consequuntur voluptas dolorem nemo. Quo praesentium amet eos repudiandae repellendus animi voluptate fuga nihil laborum, voluptatibus, deserunt aliquam, soluta beatae officiis magnam perferendis dolorum placeat incidunt quod. Expedita cumque temporibus quasi ex nesciunt dolorem fugiat ducimus laborum soluta ullam ut quas minus cum, quis animi nostrum modi at esse sapiente quisquam culpa laudantium voluptatem alias. Aspernatur culpa quibusdam maxime soluta quidem unde consequuntur veritatis quos pariatur ipsam doloribus deleniti nostrum placeat minus molestias a ipsa aliquam nemo, tempore adipisci provident! Architecto aspernatur voluptatibus doloribus nam vel sequi, mollitia consequuntur. Doloremque, cum, corporis, consequatur sequi quisquam dolor numquam qui aut ea vel similique fugit eius temporibus repellendus! Error minus officia eum tempore excepturi nemo sed, ipsa voluptate fuga ducimus suscipit similique nihil accusamus distinctio fugit blanditiis corporis? Quia earum unde expedita similique qui sed esse magnam corporis vitae aliquam sint, laborum vel tempora voluptates obcaecati harum porro sunt amet! A recusandae magni voluptas possimus laboriosam! Cupiditate voluptatem incidunt ab quaerat! Natus debitis eligendi a officiis quod inventore non perferendis, suscipit impedit in quae sunt velit architecto temporibus animi corporis laudantium nobis. Repellat fugit illo aut debitis quisquam corporis commodi. Accusamus harum quas recusandae repudiandae, dicta laudantium culpa eaque alias delectus illum impedit quos dignissimos quibusdam cum magnam cupiditate possimus, nobis aperiam. Dolores nesciunt tempora eveniet a perferendis iste iusto error exercitationem ipsum illo voluptates quos aliquam voluptatem quibusdam necessitatibus delectus ab vel, molestiae, quaerat in provident atque animi cupiditate suscipit. Eligendi maiores eius cupiditate dolore labore doloremque aliquid ipsa modi, laboriosam repellendus iure quae esse quia quisquam vel fuga, ut aspernatur? Corrupti tenetur doloribus molestiae tempora, rerum eius ex magni.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga placeat harum quis ut dolore aspernatur, vero, eaque voluptas quisquam molestias voluptates odit nulla debitis nisi corporis exercitationem a iure ipsam earum voluptatem deserunt! Optio error aut at inventore molestiae quasi quos provident voluptate architecto. Aperiam, quas ab? Beatae minus quo similique omnis debitis libero tenetur quae sit, esse assumenda dicta quam tempore expedita, repudiandae ad asperiores facilis deleniti iusto obcaecati eius cupiditate nesciunt! Ab, aut sunt? Dolorum, earum adipisci? Dolores voluptatum, numquam architecto adipisci cum neque quaerat quos! Impedit quis quisquam eaque quibusdam consequuntur corporis, vitae consectetur sint. Adipisci, ipsam!</p>
        </>
    );
}

export default About;